routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\PageController;

Auth::routes();

Route::get('/', 'PageController')->name('index');

Route::resource('catalog', 'CatalogController')->parameters([
    'catalog' => 'slug'
]);

Route::prefix('cart')->group(function () {
    Route::get('/', 'CartController@index')->name('cart.index');
    Route::get('add/{productId}', 'CartController@add')->name('cart.add');
    Route::patch('update', 'CartController@update')->name('cart.update');
    Route::get('drop', 'CartController@drop')->name('cart.drop');
    Route::get('destroy', 'CartController@destroy')->name('cart.destroy');
    Route::get('checkout', 'CartController@checkout')->name('cart.checkout');
    Route::get('success/{orderId}', 'CartController@success')->name('cart.success');
});

Route::resource('order', 'OrderController', ['only' => ['store', 'update', 'destroy', 'show']]);

// Admin Panel
Route::group(['prefix' => 'admin-panel', 'middleware' => ['auth', 'admin-panel']], function () {
//    Route::get('/', function () {
//        return "gelo";
//    });
    Route::get('/', 'AdminController')->name('admin.index');

    // Users
    Route::prefix('users')->group(function () {
        Route::get('/', 'UserController@index')->name('admin.users.index');
        Route::get('edit/{user}', 'UserController@edit')->name('admin.users.edit');
        Route::put('edit/{user}', 'UserController@update')->name('admin.users.update');
        Route::get('delete/{user}', 'UserController@delete')->name('admin.users.delete');
    });

    // Products
    Route::prefix('products')->group(function () {
        Route::get('/', 'ProductController@index')->name('admin.products.index');
        Route::get('create', 'ProductController@create')->name('admin.products.create');
        Route::post('create', 'ProductController@store')->name('admin.products.store');
        Route::get('edit/{product}', 'ProductController@edit')->name('admin.products.edit');
        Route::put('edit/{product}', 'ProductController@update')->name('admin.products.update');
        Route::get('delete/{product}', 'ProductController@delete')->name('admin.products.delete');
        Route::get('drop/{id}', 'ProductController@destroy')->name('admin.products.destroy');
        Route::get('restore/{id}', 'ProductController@restore')->name('admin.products.restore');
    });

    // Orders
    Route::prefix('orders')->group(function () {
        Route::get('/', 'OrderController@index')->name('admin.orders.index');
        Route::get('show/{id}', 'OrdersController@show')->name('admin.orders.show');
        Route::get('delete/{id}', 'OrderController@delete')->name('admin.orders.delete');
    });
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Order extends Model
{
    protected $fillable = [
        'user_id',
        'customerName',
        'customerLastName',
        'customerEmail',
        'customerPhone',
        'customerAddress',
        'comment',
        'total',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function items(): HasMany
    {
        return $this->hasMany(OrderItem::class);
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreOrderRequest;
use App\Order;
use App\OrderItem;
use App\Services\OrderService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use \Cart;

class OrderController extends Controller
{

    public function __construct(OrderService $orderService)
    {
        $this->orderService = $orderService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\StoreOrderRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreOrderRequest $request):RedirectResponse
    {
        $order = $this->orderService->storeOrder($request);

        return redirect()->route('cart.success', ['orderId' => $order->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Order $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Order $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Order $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Order $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        //
    }
}

resources/views/orders/checkout.blade.php
@extends('layouts.app')

@section('title') Checkout @endsection

@section('content')
    <div class="container wow fadeIn">

        <!-- Heading -->
        <h2 class="my-5 h2 text-center">Checkout</h2>

        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-md-8 mb-4">
                <!--Card-->
                <div class="card">
                    <!--Card content-->
                    <form class="card-body" action="{{ route('order.store') }}" method="post">
                    {{ csrf_field() }}

                    <!--Grid row-->
                        <div class="row">
                            <!--Grid column-->
                            <div class="col-md-6 mb-2">
                                <!--firstName-->
                                <div class="form-group">
                                    <label for="firstName" class="">First name</label>
                                    <input type="text" id="firstName" class="form-control" name="customerName"
                                           value="{{ auth()->user()->name ?? null }}">
                                </div>
                            </div>
                            <!--Grid column-->

                            <!--Grid column-->
                            <div class="col-md-6 mb-2">
                                <!--lastName-->
                                <div class="form-group">
                                    <label for="lastName" class="">Last name</label>
                                    <input type="text" id="lastName" class="form-control" name="customerLastName"
                                           value="{{ auth()->user()->lastname ?? null }}">
                                </div>

                            </div>
                            <!--Grid column-->

                        </div>
                        <!--Grid row-->

                        <!--email-->
                        <div class="form-group mb-5">
                            <label for="email" class="">Email</label>
                            <input type="text" id="email" class="form-control" placeholder="youremail@example.com"
                                   name="customerEmail" value="{{ auth()->user()->email ?? null }}" required>
                        </div>

                        <!--address-->
                        <div class="form-group mb-5">
                            <label for="phone" class="">Phone number</label>
                            <input type="text" id="phone" class="form-control" placeholder="+1 (123) 456-7890"
                                   name="customerPhone" value="{{ auth()->user()->phone ?? null }}">
                        </div>

                        <div class="form-group mb-5">
                            <label for="address" class="">Address</label>
                            <input type="text" id="address" class="form-control"
                                   placeholder="Park av., 123, New York, USA"
                                   name="customerAddress" value="{{ auth()->user()->address ?? null }}">
                        </div>

                        <div class="form-group mb-5">
                            <label for="comment" class="">Comment</label>
                            <textarea type="text" id="comment" class="form-control"
                                      placeholder="Comment"
                                      name="customerComment"></textarea>
                        </div>

                        <hr class="mb-4">

                        @guest
                        @else
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="save-info" name="updateUser">
                                <label class="custom-control-label" for="save-info">Save this information for next
                                    time</label>
                            </div>
                            <hr class="mb-4">
                        @endif
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Order it</button>

                    </form>

                </div>
                <!--/.Card-->

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-4 mb-4">
                <!-- Heading -->
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Your cart</span>
                    <span class="badge badge-secondary badge-pill">{{ Cart::total() }}</span>
                </h4>

                <!-- Cart -->
                <ul class="list-group mb-3 z-depth-1">
                    @foreach(Cart::content() as $item)
                        <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div>
                                <h6 class="my-0">{{ $item->name }}</h6>
                                <small class="text-muted">x {{ $item->qty }}</small>
                            </div>
                            <span class="text-muted">&dollar;{{ $item->price *  $item->qty }}</span>
                        </li>
                    @endforeach
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Total</span>
                        <strong>&dollar;{{ Cart::total() }}</strong>
                    </li>
                </ul>
                <!-- Cart -->
                <a href="{{ route('cart.index') }}" class="btn-info btn btn-lg"><i class="fa fa-arrow-left"></i> Change
                    order</a>
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->
    </div>
@endsection